[package]
name = "automancy_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
automancy_defs = { workspace = true }

syn = "2.0.66"
proc-macro2 = "1.0.85"
