[workspace]
resolver = "2"
members = [
    "build_script",
    "crates/automancy_data",
    "crates/automancy_game",
    "crates/automancy_macros",
    "crates/automancy_rendering",
    "crates/automancy_ui",
    "crates/main",
]

[workspace.package]
version = "0.1.0"
authors = [
    "Madeline Sparkles <madeline@mouse.lgbt>",
    "Mae Rosaline <mae@maestoso.online>",
]
edition = "2024"
license = "MPL-2.0"
publish = false

[workspace.dependencies]
automancy_data = { path = "crates/automancy_data" }
automancy_game = { path = "crates/automancy_game" }
automancy_macros = { path = "crates/automancy_macros" }
automancy_rendering = { path = "crates/automancy_rendering" }
automancy_system = { path = "crates/automancy_system" }
automancy_ui = { path = "crates/automancy_ui" }

# logging / profiling / tracing
log = "0.4"
profiling = { version = "1.0.17" }

# parsing / data mangling / math / files
approx = "0.5.1"
bytemuck = { version = "1.25.0", features = ["derive"] }
const-hex = "1.19.1"
crunch = "0.5.3"
easing-function = "0.1.1"
fast-srgb8 = "1.0.0"
gltf = { git = "https://github.com/gltf-rs/gltf.git" }
image = "0.25.10"
num-traits = "0.2.19"
ron = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_tuple = "1.1.3"
ttf-parser = "0.25.1"
vek = { version = "0.17.2", features = [
    "rgb",
    "rgba",
    "serde",
    "image",
    "bytemuck",
] }
zstd = "0.13.3"

# specialized data storage types
arraydeque = "0.5.1"
boomphf = { git = "https://github.com/automancy/boomphf" }
enum-map = "3.1.0"
hashbrown = { version = "0.17.1", features = ["serde", "rayon"] }
nohash-hasher = "0.2.0"
petgraph = "0.8.2"
smallvec = "1.15.1"
string-interner = { git = "https://github.com/automancy/string-interner" }

# rendering / windowing
wgpu = { version = "30.0.0", features = ["serde"] }
winit = { version = "0.30", features = ["serde"] }

# user input / user interface
arboard = "3.6.1"
kira = "0.12.0"
open = "5.3.3"
yakui = { git = "https://github.com/automancy/yakui.git", default-features = false }
yakui-wgpu = { git = "https://github.com/automancy/yakui.git" }
yakui-winit = { git = "https://github.com/automancy/yakui.git" }

# scripting / game logic / async runtime
async-stream = { version = "0.3.6" }
futures-util = { version = "0.3.32" }
ractor = "0.16.5"
rayon = "1.11.0"
rhai = { version = "1.25.1", features = [
    "sync",
    "no_time",
    "no_custom_syntax",
    "no_closure",
    "no_float",
    "only_i32",
    "metadata",
    "internals",
] }
tokio = { version = "1.52.3", features = ["full"] }

# utils
anyhow = "1.0.98"
chrono = "0.4.41"
fuzzy-matcher = { version = "0.3.7", features = ["compact"] }
include_dir = "0.7.4"
interpolator = { version = "0.5.0", features = ["number"] }
paste = "1.0"
rand = "0.10.1"
sanitize-filename = "0.6.0"
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.18"
uuid = { version = "1.23.2", features = ["v4"] }
walkdir = "2.5.0"

[profile.dev]
package."*".opt-level = 3
opt-level = 1
codegen-units = 2048
debug = "limited"
split-debuginfo = "packed"

[profile.staging]
inherits = "dev"
opt-level = 3
codegen-units = 512

[profile.release]
package."*".opt-level = "s"
opt-level = "s"
codegen-units = 32
lto = "fat"
debug = "limited"
split-debuginfo = "packed"

[patch.crates-io]
fast-srgb8 = { git = "https://github.com/automancy/fast-srgb8.git" }
