[package]
name = "automancy_game"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[features]
profile = ["profiling"]

[dependencies]
automancy_data = { workspace = true }
automancy_macros = { workspace = true }

# logging / profiling / tracing
log = { workspace = true }
profiling = { workspace = true, optional = true }

# parsing / data mangling / math / files
approx = { workspace = true }
gltf = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
ttf-parser = { workspace = true }
zstd = { workspace = true }

# specialized data storage types
arraydeque = { workspace = true }
hashbrown = { workspace = true }
petgraph = { workspace = true }

# rendering / windowing
winit = { workspace = true }

# user input / user interface
kira = { workspace = true }

# scripting / game logic / async runtime
mlua = { workspace = true }
ractor = { workspace = true }
rayon = { workspace = true }
rhai = { workspace = true }
tokio = { workspace = true }

# utils
anyhow = { workspace = true }
const_format = { workspace = true }
interpolator = { workspace = true }
rand = { workspace = true }
sanitize-filename = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
