use core::fmt;
use std::{
    fs,
    io::prelude::Write,
    path::{Path, PathBuf},
};

use automancy_data::{
    game::{coord::lua::types::TileCoord, generic::lua::doc::*, inventory::lua::doc::*},
    id::lua::types::Id,
    rendering::colors::lua::types::Rgba,
};
use const_format::formatcp;

use crate::{
    actor::tile_entity::lua::types::TileEntity,
    resources::{LUA_EXT, LUA_TYPE_DEF_EXT, LUA_TYPE_DEF_FILE, LUA_TYPE_DEF_FOLDER, MutableResourceManager, RESOURCES_PATH, SCRIPTS_PATH},
    scripting_lua::{doc::MODULE, format::types::Format, script::types::Script},
};

pub mod colors;
pub mod coord;
pub mod format;
pub mod id;
pub mod script;
pub mod tile_entity;

#[inline]
#[track_caller]
fn register_module_loader(lua: &mlua::Lua, loaders: &mlua::Table) -> mlua::Result<()> {
    const PRE: &str = "\n\t";
    const POST: &str = "the module should be formatted as {type}.{namespace}.{name}";

    let could_not_load_message = lua.create_string(formatcp!("{PRE}could not load module: error parsing module name. {POST}"))?;
    let unknown_module_message = lua.create_string(formatcp!("{PRE}could not load module: unknown module type. {POST}"))?;
    let need_exactly_two_dots_message = lua.create_string(formatcp!("{PRE}the module should have exactly two dots. {POST}"))?;
    loaders.raw_push(lua.create_function(move |lua: &mlua::Lua, modname: mlua::BorrowedStr| {
        // move inside
        let could_not_load_message = could_not_load_message.clone();
        let unknown_module_message = unknown_module_message.clone();
        let need_exactly_two_dots_message = need_exactly_two_dots_message.clone();

        if modname.chars().filter(|c| *c == '.').count() != 2 {
            return Ok(mlua::Value::String(need_exactly_two_dots_message));
        }

        // SAFETY: this function should not outlive `modname`.
        let modname = unsafe { &*(&*(modname) as *const str) };
        let mut components = modname.split(".");

        match (components.next(), components.next(), components.next()) {
            (Some(ty), Some(namespace), Some(name)) => Ok(mlua::Value::Function(lua.create_function(move |lua, ()| {
                let mut path = PathBuf::new();
                path.push(RESOURCES_PATH);
                path.push(namespace);
                path.push(SCRIPTS_PATH);
                path.push(ty);
                // `name` is normalized to be separated by /
                for component in name.split("/") {
                    path.push(component);
                }
                path.set_extension(LUA_EXT);

                match ty {
                    "lib" => Ok(mlua::Value::Table(MutableResourceManager::load_script_file_lib_lua(
                        &path, namespace, name, lua,
                    )?)),
                    _ => Ok(mlua::Value::String(unknown_module_message.clone())),
                }
            })?)),
            _ => Ok(mlua::Value::String(could_not_load_message.clone())),
        }
    })?)?;

    Ok(())
}

#[inline]
#[track_caller]
fn register_all(lua: &mlua::Lua) -> mlua::Result<()> {
    {
        const HEADER: &str = "---AUTOMATICALLY GENERATED BY AUTOMANCY AT RUNTIME: DO NOT EDIT!
";

        let lua_type_defs = Path::new(LUA_TYPE_DEF_FOLDER);
        fs::create_dir_all(lua_type_defs).unwrap();

        let mut type_def = String::from(HEADER);
        fmt::write(
            &mut type_def,
            const_format_args!(
                "---@meta _

{DATA_MAP}

{ITEM_AMOUNT}

{ITEM_STACK}

{INVENTORY}

{MODULE}
"
            ),
        )
        .unwrap();

        {
            let mut type_def = String::from(HEADER);
            fmt::write(
                &mut type_def,
                const_format_args!(
                    "---@meta {Rgba}

"
                ),
            )
            .unwrap();

            colors::register_lua(lua, &mut type_def)?;
            fs::File::create(lua_type_defs.join(Rgba).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
        }

        {
            let mut type_def = String::from(HEADER);
            fmt::write(
                &mut type_def,
                const_format_args!(
                    "---@meta {Id}

"
                ),
            )
            .unwrap();

            id::register_lua(lua, &mut type_def)?;
            fs::File::create(lua_type_defs.join(Id).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
        }

        {
            let mut type_def = String::from(HEADER);
            fmt::write(
                &mut type_def,
                const_format_args!(
                    "---@meta {TileCoord}

"
                ),
            )
            .unwrap();

            coord::register_lua(lua, &mut type_def)?;
            fs::File::create(lua_type_defs.join(TileCoord).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
        }

        {
            let mut type_def = String::from(HEADER);
            fmt::write(
                &mut type_def,
                const_format_args!(
                    "---@meta {Format}

"
                ),
            )
            .unwrap();

            format::register_lua(lua, &mut type_def)?;
            fs::File::create(lua_type_defs.join(Format).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
        }

        {
            let mut type_def = String::from(HEADER);
            fmt::write(
                &mut type_def,
                const_format_args!(
                    "---@meta {TileEntity}

"
                ),
            )
            .unwrap();

            tile_entity::register_lua(lua, &mut type_def)?;
            fs::File::create(lua_type_defs.join(TileEntity).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
        }

        {
            let mut type_def = String::from(HEADER);
            fmt::write(
                &mut type_def,
                const_format_args!(
                    "---@meta {Script}

"
                ),
            )
            .unwrap();

            script::register_lua(lua, &mut type_def)?;
            fs::File::create(lua_type_defs.join(Script).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
        }

        fs::File::create(lua_type_defs.join(LUA_TYPE_DEF_FILE).with_extension(LUA_TYPE_DEF_EXT))?.write_all(type_def.as_bytes())?;
    }

    Ok(())
}

pub fn setup(lua: &mlua::Lua) -> mlua::Result<()> {
    // don't allow these
    lua.globals().raw_remove("dofile")?;
    lua.globals().raw_remove("load")?;
    lua.globals().raw_remove("loadfile")?;
    lua.globals().raw_remove("loadstring")?;
    lua.globals().raw_remove("setfenv")?;
    lua.globals().raw_remove("getfenv")?;

    let package = lua.globals().raw_get::<mlua::Table>("package")?;

    {
        let loaders = package.raw_get::<mlua::Table>("loaders")?;
        // Remove all but the first loader.
        // The first searcher simply looks for a loader in the package.preload table.
        // The rest searches for files, we don't want that.
        //
        // https://www.lua.org/manual/5.1/manual.html#pdf-require
        for _ in 1..loaders.len()? {
            loaders.raw_pop::<mlua::Value>()?;
        }
        register_module_loader(lua, &loaders)?;
    }

    register_all(lua)?;

    // lock globals
    lua.globals().raw_remove("_G")?;

    Ok(())
}
