[package]
name = "automancy_macros"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
proc-macro = true

[dependencies]
automancy_data = { workspace = true }

proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
